# Generated by Django 5.2.17 on 2026-10-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='dealer_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
